In [1]:
import numpy as np

Creating numpy array from python lists

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
[3.14, 1, 2, 3]

[3.14, 1, 2, 3]

In [4]:
np.array([3.14, 1, 3, 4])

array([3.14, 1.  , 3.  , 4.  ])

In [5]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1, 2, 3, 4])
type(a1)

numpy.ndarray

In [7]:
a1.ndim

1

In [8]:
a1.shape

(4,)

In [9]:
a2 = np.array([[1,2,3],
               [4,5,6]])
type(a2)

numpy.ndarray

In [10]:
a2.shape

(2, 3)

In [11]:
a2.ndim

2

In [12]:
a2.dtype

dtype('int32')

In [13]:
a2.size

6

Creating Numpy Array from Scratch

zeros, one, full, arange, linspace

In [14]:
np.zeros((2,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
a = np.arange(0,20,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
a.ndim

1

In [18]:
a.shape

(10,)

In [19]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

random

In [21]:
np.random.random((4,4))

array([[0.78177815, 0.1275594 , 0.34776779, 0.03654152],
       [0.9728656 , 0.97974884, 0.61209886, 0.12694557],
       [0.62597695, 0.28610354, 0.56359769, 0.40604936],
       [0.16208046, 0.21769323, 0.28487554, 0.99898953]])

In [22]:
#seed for reproducibility
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [23]:
np.random.normal(0,1,(3,3))     #random với theo phân bố gaussian với độ lệch chuẩn là 1

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [24]:
np.random.randint(0,10,(4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [25]:
np.random.rand(4,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

Array Indexing and Slicing

One-dimensional subarray

In [26]:
x1 = np.random.randint(20, size=6)

In [27]:
x1

array([15, 13, 16, 17,  5,  9])

In [28]:
x1[4], x1[0], x1[-1]

(5, 15, 9)

Mutil-dimensional array

In [29]:
x2 = np.random.randint(10, size= (3,4))

In [30]:
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [31]:
x2[1,2]

4

slicing:

x[start:stop:step]

In [32]:
x1

array([15, 13, 16, 17,  5,  9])

In [33]:
x1[0:3]

array([15, 13, 16])

In [34]:
x1[::2]

array([15, 16,  5])

In [35]:
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [36]:
x2[:2, :3]

array([[3, 0, 5],
       [1, 2, 4]])

In [37]:
x2[:, :2]

array([[3, 0],
       [1, 2],
       [0, 3]])

Reshaping of Array & Transpose

In [38]:
grid = np.arange(1, 10)
grid.shape

(9,)

In [39]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
x = np.array([1, 2, 3])

In [41]:
x.shape

(3,)

In [42]:
x.reshape((1,3)).shape

(1, 3)

Transpoe ==> ma trận chuyển vị

In [43]:
x = np.array([[1., 2.],[3., 4.]])

In [44]:
x

array([[1., 2.],
       [3., 4.]])

In [45]:
type(x)

numpy.ndarray

In [46]:
x.T

array([[1., 3.],
       [2., 4.]])

Array Concatenation and Splitting

In [47]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [48]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [49]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
x = np.concatenate((grid,grid), axis=1)
x

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
x.ndim

2

In [53]:
y = np.array([[99],
              [99]])
np.hstack((y,grid))

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

Splitting of arrays

In [54]:
x = np.array([1,2,3,99,69,3,2,1])

In [55]:
x1, x2, x3 = np.split(x, [3,5])

In [56]:
x1

array([1, 2, 3])

In [57]:
x2

array([99, 69])

Broadcasting and Vectorized operations

In [58]:
a = np.arange(3)
a

array([0, 1, 2])

In [59]:
a + 5   #broadcasting

array([5, 6, 7])

In [60]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
a.shape, b.shape

((3,), (3, 3))

In [62]:
a.ndim

1

In [63]:
b.ndim

2

In [64]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [65]:
c = np.arange(3).reshape((3,1))

In [66]:
c

array([[0],
       [1],
       [2]])

In [67]:
c.ndim

2

In [68]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Manipulating & Comparing Arrays

Aggregation

Aggregation = performkng the same operation on a number of things

In [69]:
list_number = [1, 2, 3]

In [70]:
ll = np.array(list_number)

In [71]:
ll

array([1, 2, 3])

In [72]:
sum(ll)     #Python sum()

6

In [73]:
np.sum(ll)

6

In [74]:
massive_array = np.random.random(10000)
massive_array[: 5]
massive_array.shape

(10000,)

In [75]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

993 µs ± 116 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
9.52 µs ± 1.43 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [76]:
np.mean(massive_array)  # tổng tb

0.49644077223750666

In [77]:
np.max(massive_array)

0.9999779517807228

độ lệch chuẩn và phương sai

In [78]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)
np.std(dog_height)

147.32277488562318

In [79]:
np.var(dog_height)

21704.0

In [80]:
np.sqrt(np.var(dog_height))

147.32277488562318

Sorting Arrays

In [81]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [82]:
np.argsort(x)

array([1, 0, 3, 2, 4], dtype=int64)

sorting along rows or columns

In [83]:
np.random.seed(42)

MatA = np.random.randint(0, 10, size=(4,6))

In [84]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [85]:
np.sort(MatA, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [86]:
np.sort(MatA, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

Đại số tuyến tính

In [87]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [88]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [89]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

Dot product Example

In [90]:
np.random.seed(0)

sales_amonunts = np.random.randint(20, size=(5,3))

In [91]:
import pandas as pd

weekly_sales = pd.DataFrame(sales_amonunts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                                            columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [92]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [93]:
# create a price array

prices = np.array([10, 8, 12])

In [94]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["prices"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [95]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
prices             10              8             12

In [96]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [97]:
total_prices = weekly_sales.dot(butter_prices.T)

In [98]:
total_prices

prices
Mon       240
Tues      138
Wed       458
Thurs     232
Fri       142

In [99]:
weekly_sales["total_prices"] = total_prices
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  total_prices
Mon               12             15              0           240
Tues               3              3              7           138
Wed                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142